<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>demo</artifactId>
    <groupId>com.regnosys.model</groupId>
    <version>0.0.0.master-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.regnosys.model.demo</groupId>
  <artifactId>demo-tests</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.regnosys.model.demo</groupId>
      <artifactId>rosetta-source</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.finos.rune-common</groupId>
      <artifactId>rune-common</artifactId>
    </dependency>

    <dependency>
      <groupId>org.finos.rune-common</groupId>
      <artifactId>serialization</artifactId>
    </dependency>

    <dependency>
      <groupId>org.finos.rune-testing</groupId>
      <artifactId>rune-testing</artifactId>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>update-expectations</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <executions>
              <execution>
                <phase>process-test-classes</phase>
                <goals>
                  <goal>exec</goal>
                </goals>
                <configuration>
                  <executable>java</executable>
                  <classpathScope>test</classpathScope>
                  <arguments>
                    <argument>-classpath</argument>
                    <classpath/>
                    <argument>com.regnosys.demo.DemoTestPackCreator</argument>
                  </arguments>
                  <environmentVariables>
                    <WRITE_EXPECTATIONS>true</WRITE_EXPECTATIONS>
                    <CREATE_EXPECTATION_FILES>true</CREATE_EXPECTATION_FILES>
                    <UPDATE_OR_CREATE_MODEL_DIFFS>true</UPDATE_OR_CREATE_MODEL_DIFFS>
                    <TEST_WRITE_BASE_PATH>${maven.multiModuleProjectDirectory}/rosetta-source/src/main/resources</TEST_WRITE_BASE_PATH>
                  </environmentVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <executions>
          <execution>
            <id>default-compile</id>
            <phase>none</phase>
          </execution>
          <execution>
            <id>default-testCompile</id>
            <phase>none</phase>
          </execution>
          <execution>
            <id>java-compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>java-test-compile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
