model:
  name: DEMO
dependencies:
generators:
  namespaces:
  - demo.*
  - com.rosetta.model
  tabulators:
    types:
      - demo.emissions.VehicleOwnership
      - demo.translate.conditional_default.example_1.Root
      - demo.translate.conditional_set.example_1.Root
      - demo.translate.conditional_set.example_2.Root
      - demo.translate.conditional_set.example_3.Root
      - demo.translate.conditional_set.example_4.Root
      - demo.translate.conditional_set.example_5.Root
      - demo.translate.conditional_set.example_6.Root
      - demo.translate.conditional_set.example_7.Root
      - demo.translate.conditional_set.example_8.Root
      - demo.translate.conditional_set.example_9.Root
      - demo.translate.conditional_set.example_10.Root
      - demo.translate.conditional_set.example_11.Root
      - demo.translate.conditional_set.example_12.Root
      - demo.translate.conditional_set.example_13.Root
      - demo.translate.conditional_set.example_14.Root
      - demo.translate.conditional_set.example_15.Root
      - demo.translate.conditional_set.example_16.Root
      - demo.translate.conditional_set.example_17.Root
      - demo.translate.conditional_set.example_18.Root
      - demo.translate.conditional_set.example_19.Root
      - demo.translate.conditional_set.example_20.Root
      - demo.translate.conditional_set.example_21.Root
      - demo.translate.conditional_set.example_22.Root
      - demo.translate.conditional_set.example_23.Root
      - demo.translate.conditional_set.example_24.Root
      - demo.translate.conditional_set.example_25.Root
      - demo.translate.conditional_set.example_26.Root
      - demo.translate.conditional_set_to.example_1.Root
      - demo.translate.conditional_set_to.example_2.Root
      - demo.translate.conditional_set_to.example_3.Root
      - demo.translate.conditional_set_to.example_4.Root
      - demo.translate.conditional_set_to.example_5.Root
      - demo.translate.conditional_set_to.example_6.Root
      - demo.translate.conditional_set_to.example_7.Root
      - demo.translate.conditional_set_to.example_8.Root
      - demo.translate.conditional_set_to.example_9.Root
      - demo.translate.conditional_set_to.example_10.Root
      - demo.translate.conditional_set_to.example_11.Root
      - demo.translate.conditional_set_to.example_12.Root
      - demo.translate.conditional_set_to.example_13.Root
      - demo.translate.external_synonym.example_1.Root
      - demo.translate.external_synonym.example_2.Root
      - demo.translate.external_synonym.example_3.Root
      - demo.translate.external_synonym.example_4.Root
      - demo.translate.external_synonym.example_5.Root
      - demo.translate.external_synonym.example_6.Root
      - demo.translate.external_synonym.example_7.Root
      - demo.translate.external_synonym.example_8.Root
      - demo.translate.format.example_1.Root
      - demo.translate.format.example_2.Root
      - demo.translate.mappers.example_1.Root
      - demo.translate.mappers.example_2.Root
      - demo.translate.mappers.example_3.Root
      - demo.translate.mappers.example_4.Root
      - demo.translate.mappers.example_5.Root
      - demo.translate.mappers.example_6.Root
      - demo.translate.mappers.example_7.Root
      - demo.translate.mappers.example_8.Root
      - demo.translate.mappers.example_9.Root
      - demo.translate.mappers.example_10.Root
      - demo.translate.mappers.example_11.Root
      - demo.translate.mappers.example_12.Root
      - demo.translate.meta_external_reference.example_1.Root
      - demo.translate.meta_external_reference.example_2.Root
      - demo.translate.meta_external_reference.example_3.Root
      - demo.translate.meta_external_reference.example_4.Root
      - demo.translate.meta_external_reference.example_5.Root
      - demo.translate.meta_external_reference.example_6.Root
      - demo.translate.meta_scheme.example_1.Root
      - demo.translate.meta_scoped_reference.example_1.Root
      - demo.translate.meta_scoped_reference.example_2.Root
      - demo.translate.multi_cardinality.example_1.Root
      - demo.translate.multi_cardinality.example_2.Root
      - demo.translate.multi_cardinality.example_3.Root
      - demo.translate.multi_cardinality.example_4.Root
      - demo.translate.multi_cardinality.example_5.Root
      - demo.translate.multi_cardinality.example_6.Root
      - demo.translate.multi_cardinality.example_7.Root
      - demo.translate.multi_cardinality.example_8.Root
      - demo.translate.multi_cardinality.example_9.Root
      - demo.translate.multi_cardinality.example_10.Root
      - demo.translate.multi_cardinality.example_11.Root
      - demo.translate.multi_cardinality.example_12.Root
      - demo.translate.multi_cardinality.example_13.Root
      - demo.translate.multi_cardinality.example_14.Root
      - demo.translate.multi_cardinality.example_15.Root
      - demo.translate.multi_cardinality.example_16.Root
      - demo.translate.multi_cardinality.example_17.Root
      - demo.translate.multi_cardinality.example_18.Root
      - demo.translate.multi_cardinality.example_19.Root
      - demo.translate.multi_cardinality.example_20.Root
      - demo.translate.multi_cardinality.example_21.Root
      - demo.translate.multi_cardinality.example_22.Root
      - demo.translate.multi_cardinality.example_23.Root
      - demo.translate.multi_cardinality.example_24.Root
      - demo.translate.multi_cardinality.example_25.Root
      - demo.translate.multi_cardinality.example_26.Root
      - demo.translate.multi_cardinality.example_27.Root
      - demo.translate.multi_cardinality.example_28.Root
      - demo.translate.single_cardinality.example_1.Root
      - demo.translate.single_cardinality.example_2.Root
      - demo.translate.single_cardinality.example_3.Root
      - demo.translate.single_cardinality.example_4.Root
      - demo.translate.single_cardinality.example_5.Root
      - demo.translate.single_cardinality.example_6.Root
      - demo.translate.type_inheritance.example_1.Root
      - demo.translate.type_inheritance.example_2.Root
