name: Demo Model CVE Scanning

on:
  push:
    branches:
      - master
    paths: &monitored-files
      - 'pom.xml'
      - 'CVE-suppressions.xml'
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths: *monitored-files

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CVSS_THRESHOLD: 7
  REPORT_FORMAT: HTML
  REPORTS_DIR: reports
  JAVA_VERSION: '21'

jobs:
  cve-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project
        run: mvn compile -DskipTests

      - name: Run OSS Index CVE scan
        run: |
          mkdir -p ${{ env.REPORTS_DIR }}
          mvn org.sonatype.ossindex.maven:ossindex-maven-plugin:audit \
            -Dossindex.fail=true \
            -Dossindex.cvssScoreThreshold=${{ env.CVSS_THRESHOLD }} \
            -Dossindex.reportFile=${{ env.REPORTS_DIR }}/ossindex-report.json

      - name: Generate HTML report from OSS Index results
        if: always()
        run: |
          cat > ${{ env.REPORTS_DIR }}/cve-report.html << 'EOF'
          <!DOCTYPE html>
          <html><head><title>OSS Index CVE Scan Report</title></head>
          <body><h1>CVE Scan Results</h1>
          <pre>$(cat ${{ env.REPORTS_DIR }}/ossindex-report.json 2>/dev/null || echo "No vulnerabilities found")</pre>
          </body></html>
          EOF

      - name: Upload CVE scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CVE Security Scan Report
          path: ${{ github.workspace }}/${{ env.REPORTS_DIR }}