name: Demo Model CVE Scanning

on:
  push:
    branches:
      - master
    paths: &monitored-files
      - 'pom.xml'
      - 'CVE-suppressions.xml'
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths: *monitored-files

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CVSS_THRESHOLD: 7
  REPORT_FORMAT: HTML
  REPORTS_DIR: reports

jobs:
  cve-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/maven-build
        with:
          run-tests: false

      - name: Run CVE security scan
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: ${{ github.repository }}
          path: '.'
          format: ${{ env.REPORT_FORMAT }}
          out: ${{ env.REPORTS_DIR }}
          args: >
            --suppression CVE-suppressions.xml
            --failOnCVSS ${{ env.CVSS_THRESHOLD }}

      - name: Upload CVE scan results
        uses: actions/upload-artifact@v4
        with:
          name: CVE Security Scan Report
          path: ${{ github.workspace }}/${{ env.REPORTS_DIR }}