name: Demo Model CVE Scanning

on:
  push:
    branches:
      - master
    paths: &monitored-files
      - '**/pom.xml'  # Monitor all POM files
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths: *monitored-files

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write   # Required for Workload Identity Federation
  contents: read    # Required for actions/checkout

env:
  CVSS_THRESHOLD: 7
  REPORT_FORMAT: HTML
  REPORTS_DIR: reports
  JAVA_VERSION: '21'  # Match the project's compiler version

jobs:
  cve-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: production-208613
          workload_identity_provider: projects/211964611435/locations/global/workloadIdentityPools/artifact-registry/providers/github-actions-demo-model
#          service_account: codefresh-artifactory-docker@production-208613.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build modules to populate local repo (no tests)
        run: mvn -B -ntp -U -DskipTests install
      - name: Run CVE scan on source files and POM structure
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: ${{ github.repository }}
          path: '.'
          format: ${{ env.REPORT_FORMAT }}
          out: ${{ env.REPORTS_DIR }}
          args: >
            --failOnCVSS ${{ env.CVSS_THRESHOLD }}
        env:
          JAVA_HOME: ""
          JAVA_HOME_21_X64: ""
      - name: Upload CVE scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CVE Security Scan Report
          path: ${{ github.workspace }}/${{ env.REPORTS_DIR }}