name: Demo Model CVE Scanning

on:
  push:
    branches:
      - master
    paths: &monitored-files
      - '**/pom.xml'  # Monitor all POM files
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths: *monitored-files

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write   # Required for Workload Identity Federation
  contents: read    # Required for actions/checkout
  security-events: write  # Required for uploading SARIF results

env:
  JAVA_VERSION: '21'  # Match the project's compiler version

jobs:
  cve-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: production-208613
          workload_identity_provider: projects/211964611435/locations/global/workloadIdentityPools/artifact-registry/providers/github-actions-demo-model
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build modules to populate local repo (no tests)
        run: mvn -B -ntp -U -DskipTests install
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'  # Don't fail the build, just report
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Generate HTML report
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          output: 'trivy-results.html'
          severity: 'HIGH,CRITICAL'
      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CVE Security Scan Report
          path: |
            trivy-results.sarif
            trivy-results.html