name: Demo Model CVE Scanning

on:
  push:
    branches:
      - master
    paths: &monitored-files
      - 'pom.xml'
      - 'CVE-suppressions.xml'
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths: *monitored-files

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CVSS_THRESHOLD: 7
  REPORT_FORMAT: HTML
  REPORTS_DIR: reports

jobs:
  cve-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/maven-build
        with:
          run-tests: false

      - name: Run OSS Index CVE scan
        run: |
          mvn org.sonatype.ossindex.maven:ossindex-maven-plugin:audit \
            -Dossindex.fail=true \
            -Dossindex.cvssScoreThreshold=${{ env.CVSS_THRESHOLD }} \
            -Dossindex.reportFile=${{ env.REPORTS_DIR }}/ossindex-report.json
        env:
          JAVA_HOME: /opt/jdk

      - name: Generate HTML report from OSS Index results
        run: |
          mkdir -p ${{ env.REPORTS_DIR }}
          # Convert JSON report to HTML format
          cat > ${{ env.REPORTS_DIR }}/cve-report.html << 'EOF'
          <!DOCTYPE html>
          <html><head><title>OSS Index CVE Scan Report</title></head>
          <body><h1>CVE Scan Results</h1>
          <pre>$(cat ${{ env.REPORTS_DIR }}/ossindex-report.json 2>/dev/null || echo "No vulnerabilities found")</pre>
          </body></html>
          EOF

      - name: Upload CVE scan results
        uses: actions/upload-artifact@v4
        with:
          name: CVE Security Scan Report
          path: ${{ github.workspace }}/${{ env.REPORTS_DIR }}