name: Demo Model CVE Scanning

on:
  push:
    branches:
      - master
    paths: &monitored-files
      - '**/pom.xml'  # Monitor all POM files
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths: *monitored-files

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write   # Required for Workload Identity Federation
  contents: read    # Required for actions/checkout

env:
  CVSS_THRESHOLD: 7
  REPORT_FORMAT: HTML
  REPORTS_DIR: reports
  JAVA_VERSION: '21'  # Match the project's compiler version

jobs:
  cve-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: production-208613
          workload_identity_provider: projects/211964611435/locations/global/workloadIdentityPools/artifact-registry/providers/github-actions-demo-model
#          service_account: codefresh-artifactory-docker@production-208613.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache OWASP Dependency-Check database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-owasp-db-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-owasp-db-
      - name: Build modules to populate local repo (no tests)
        run: mvn -B -ntp -U -DskipTests install
      - name: Run OWASP Dependency-Check (Maven plugin)
        run: |
          mkdir -p "${{ env.REPORTS_DIR }}"
          mvn -B -ntp org.owasp:dependency-check-maven:9.2.0:check \
            -Dformat=${{ env.REPORT_FORMAT }} \
            -DfailOnCVSS=${{ env.CVSS_THRESHOLD }} \
            -DoutputDirectory=${{ env.REPORTS_DIR }} \
            -DnvdMaxRetryCount=10 \
            -DnvdDelay=4000 \
            -DconnectionTimeout=120000 \
            -DreadTimeout=120000
      - name: Upload CVE scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CVE Security Scan Report
          path: ${{ github.workspace }}/${{ env.REPORTS_DIR }}