name: Demo Model CVE Scanning

on:
  push:
    branches:
      - master
    paths: &monitored-files
      - '**/pom.xml'  # Monitor all POM files
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths: *monitored-files

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write   # Required for Workload Identity Federation
  contents: read    # Required for actions/checkout

env:
  JAVA_VERSION: '21'  # Match the project's compiler version

jobs:
  cve-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: production-208613
          workload_identity_provider: projects/211964611435/locations/global/workloadIdentityPools/artifact-registry/providers/github-actions-demo-model
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build modules to populate local repo (no tests)
        run: mvn -B -ntp -U -DskipTests install
      - name: Run Trivy vulnerability scanner (JSON)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
      - name: Run Trivy vulnerability scanner (Table for HTML)
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'
      - name: Convert table to HTML
        if: always()
        run: |
          echo "<html><head><title>Trivy Security Scan Report</title></head><body><h1>🛡️ Trivy Security Scan Report</h1><pre>" > trivy-results.html
          cat trivy-results.txt >> trivy-results.html
          echo "</pre></body></html>" >> trivy-results.html
      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CVE Security Scan Report
          path: |
            trivy-results.json
            trivy-results.html
            trivy-results.txt